/* ds.h generated by valac 0.10.1, the Vala compiler, do not modify */


#ifndef __POLYOL_DS_H__
#define __POLYOL_DS_H__

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <polyol/env.h>

G_BEGIN_DECLS


#define SUGAR_TYPE_JOBJECT (sugar_jobject_get_type ())
#define SUGAR_JOBJECT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SUGAR_TYPE_JOBJECT, SugarJobject))
#define SUGAR_JOBJECT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SUGAR_TYPE_JOBJECT, SugarJobjectClass))
#define SUGAR_IS_JOBJECT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SUGAR_TYPE_JOBJECT))
#define SUGAR_IS_JOBJECT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SUGAR_TYPE_JOBJECT))
#define SUGAR_JOBJECT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SUGAR_TYPE_JOBJECT, SugarJobjectClass))

typedef struct _SugarJobject SugarJobject;
typedef struct _SugarJobjectClass SugarJobjectClass;
typedef struct _SugarJobjectPrivate SugarJobjectPrivate;

struct _SugarJobject {
	GObject parent_instance;
	SugarJobjectPrivate * priv;
};

struct _SugarJobjectClass {
	GObjectClass parent_class;
};


GType sugar_jobject_get_type (void) G_GNUC_CONST;
SugarJobject* sugar_jobject_create (void);
SugarJobject* sugar_jobject_find (const char* uid);
GValue* sugar_jobject_get_field (SugarJobject* self, const char* field_name);
void sugar_jobject_set_field (SugarJobject* self, const char* field_name, GValue* field_value);
void sugar_jobject_write (SugarJobject* self);
void sugar_jobject_write_file (SugarJobject* self, const char* file_path, gboolean transfer_ownership);
void sugar_jobject_cow (SugarJobject* self);
gboolean sugar_jobject_unlink (SugarJobject* self);
const char* _sugar_jobject_get_string (SugarJobject* self, const char* field_name);
void _sugar_jobject_set_string (SugarJobject* self, const char* field_name, const char* field_value);
void _sugar_jobject_set_field (SugarJobject* self, const char* field_name, GValue* field_value);
const char* sugar_jobject_get_uid (SugarJobject* self);
glong sugar_jobject_get_timestamp (SugarJobject* self);
void sugar_jobject_set_timestamp (SugarJobject* self, glong value);
const char* sugar_jobject_get_title (SugarJobject* self);
void sugar_jobject_set_title (SugarJobject* self, const char* value);
gboolean sugar_jobject_get_title_set_by_user (SugarJobject* self);
void sugar_jobject_set_title_set_by_user (SugarJobject* self, gboolean value);
const char* sugar_jobject_get_mime_type (SugarJobject* self);
void sugar_jobject_set_mime_type (SugarJobject* self, const char* value);
SugarShareScope sugar_jobject_get_share_scope (SugarJobject* self);
void sugar_jobject_set_share_scope (SugarJobject* self, SugarShareScope value);
const char* sugar_jobject_get_activity (SugarJobject* self);
void sugar_jobject_set_activity (SugarJobject* self, const char* value);
const char* sugar_jobject_get_activity_id (SugarJobject* self);
void sugar_jobject_set_activity_id (SugarJobject* self, const char* value);
gboolean sugar_jobject_get_keep (SugarJobject* self);
void sugar_jobject_set_keep (SugarJobject* self, gboolean value);
GArray* sugar_jobject_get_preview (SugarJobject* self);
void sugar_jobject_set_preview (SugarJobject* self, GArray* value);
void sugar_jobject_get_icon_color (SugarJobject* self, SugarXoColor* result);
void sugar_jobject_set_icon_color (SugarJobject* self, SugarXoColor* value);
const char* sugar_jobject_get_file_path (SugarJobject* self);


G_END_DECLS

#endif
