/* gui.h generated by valac 0.10.1, the Vala compiler, do not modify */


#ifndef __POLYOL_GUI_H__
#define __POLYOL_GUI_H__

#include <glib.h>
#include <float.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <gdk/gdk.h>
#include <polyol/env.h>
#include <cairo.h>
#include <gdk-pixbuf/gdk-pixdata.h>

G_BEGIN_DECLS


#define SUGAR_TYPE_RANGE (sugar_range_get_type ())
typedef struct _SugarRange SugarRange;

#define SUGAR_TYPE_TIMESTAMP (sugar_timestamp_get_type ())
typedef struct _SugarTimestamp SugarTimestamp;

#define SUGAR_TYPE_TRIGGER (sugar_trigger_get_type ())
#define SUGAR_TRIGGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SUGAR_TYPE_TRIGGER, SugarTrigger))
#define SUGAR_TRIGGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SUGAR_TYPE_TRIGGER, SugarTriggerClass))
#define SUGAR_IS_TRIGGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SUGAR_TYPE_TRIGGER))
#define SUGAR_IS_TRIGGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SUGAR_TYPE_TRIGGER))
#define SUGAR_TRIGGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SUGAR_TYPE_TRIGGER, SugarTriggerClass))

typedef struct _SugarTrigger SugarTrigger;
typedef struct _SugarTriggerClass SugarTriggerClass;
typedef struct _SugarTriggerPrivate SugarTriggerPrivate;

#define SUGAR_TYPE_CONTAINER (sugar_container_get_type ())
#define SUGAR_CONTAINER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SUGAR_TYPE_CONTAINER, SugarContainer))
#define SUGAR_CONTAINER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SUGAR_TYPE_CONTAINER, SugarContainerClass))
#define SUGAR_IS_CONTAINER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SUGAR_TYPE_CONTAINER))
#define SUGAR_IS_CONTAINER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SUGAR_TYPE_CONTAINER))
#define SUGAR_CONTAINER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SUGAR_TYPE_CONTAINER, SugarContainerClass))

typedef struct _SugarContainer SugarContainer;
typedef struct _SugarContainerClass SugarContainerClass;
typedef struct _SugarContainerPrivate SugarContainerPrivate;

#define SUGAR_TYPE_BOX (sugar_box_get_type ())
#define SUGAR_BOX(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SUGAR_TYPE_BOX, SugarBox))
#define SUGAR_BOX_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SUGAR_TYPE_BOX, SugarBoxClass))
#define SUGAR_IS_BOX(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SUGAR_TYPE_BOX))
#define SUGAR_IS_BOX_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SUGAR_TYPE_BOX))
#define SUGAR_BOX_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SUGAR_TYPE_BOX, SugarBoxClass))

typedef struct _SugarBox SugarBox;
typedef struct _SugarBoxClass SugarBoxClass;
typedef struct _SugarBoxPrivate SugarBoxPrivate;

#define SUGAR_TYPE_BIN (sugar_bin_get_type ())
#define SUGAR_BIN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SUGAR_TYPE_BIN, SugarBin))
#define SUGAR_BIN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SUGAR_TYPE_BIN, SugarBinClass))
#define SUGAR_IS_BIN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SUGAR_TYPE_BIN))
#define SUGAR_IS_BIN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SUGAR_TYPE_BIN))
#define SUGAR_BIN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SUGAR_TYPE_BIN, SugarBinClass))

typedef struct _SugarBin SugarBin;
typedef struct _SugarBinClass SugarBinClass;
typedef struct _SugarBinPrivate SugarBinPrivate;

#define SUGAR_TYPE_PAINT_BIN (sugar_paint_bin_get_type ())
#define SUGAR_PAINT_BIN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SUGAR_TYPE_PAINT_BIN, SugarPaintBin))
#define SUGAR_PAINT_BIN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SUGAR_TYPE_PAINT_BIN, SugarPaintBinClass))
#define SUGAR_IS_PAINT_BIN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SUGAR_TYPE_PAINT_BIN))
#define SUGAR_IS_PAINT_BIN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SUGAR_TYPE_PAINT_BIN))
#define SUGAR_PAINT_BIN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SUGAR_TYPE_PAINT_BIN, SugarPaintBinClass))

typedef struct _SugarPaintBin SugarPaintBin;
typedef struct _SugarPaintBinClass SugarPaintBinClass;
typedef struct _SugarPaintBinPrivate SugarPaintBinPrivate;

#define SUGAR_TYPE_TOOL_TEXT (sugar_tool_text_get_type ())
#define SUGAR_TOOL_TEXT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SUGAR_TYPE_TOOL_TEXT, SugarToolText))
#define SUGAR_TOOL_TEXT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SUGAR_TYPE_TOOL_TEXT, SugarToolTextClass))
#define SUGAR_IS_TOOL_TEXT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SUGAR_TYPE_TOOL_TEXT))
#define SUGAR_IS_TOOL_TEXT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SUGAR_TYPE_TOOL_TEXT))
#define SUGAR_TOOL_TEXT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SUGAR_TYPE_TOOL_TEXT, SugarToolTextClass))

typedef struct _SugarToolText SugarToolText;
typedef struct _SugarToolTextClass SugarToolTextClass;
typedef struct _SugarToolTextPrivate SugarToolTextPrivate;

#define SUGAR_TYPE_HOMOGENE_TABLE (sugar_homogene_table_get_type ())
#define SUGAR_HOMOGENE_TABLE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SUGAR_TYPE_HOMOGENE_TABLE, SugarHomogeneTable))
#define SUGAR_HOMOGENE_TABLE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SUGAR_TYPE_HOMOGENE_TABLE, SugarHomogeneTableClass))
#define SUGAR_IS_HOMOGENE_TABLE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SUGAR_TYPE_HOMOGENE_TABLE))
#define SUGAR_IS_HOMOGENE_TABLE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SUGAR_TYPE_HOMOGENE_TABLE))
#define SUGAR_HOMOGENE_TABLE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SUGAR_TYPE_HOMOGENE_TABLE, SugarHomogeneTableClass))

typedef struct _SugarHomogeneTable SugarHomogeneTable;
typedef struct _SugarHomogeneTableClass SugarHomogeneTableClass;
typedef struct _SugarHomogeneTablePrivate SugarHomogeneTablePrivate;

#define SUGAR_TYPE_TOOL_BUTTON (sugar_tool_button_get_type ())
#define SUGAR_TOOL_BUTTON(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SUGAR_TYPE_TOOL_BUTTON, SugarToolButton))
#define SUGAR_TOOL_BUTTON_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SUGAR_TYPE_TOOL_BUTTON, SugarToolButtonClass))
#define SUGAR_IS_TOOL_BUTTON(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SUGAR_TYPE_TOOL_BUTTON))
#define SUGAR_IS_TOOL_BUTTON_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SUGAR_TYPE_TOOL_BUTTON))
#define SUGAR_TOOL_BUTTON_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SUGAR_TYPE_TOOL_BUTTON, SugarToolButtonClass))

typedef struct _SugarToolButton SugarToolButton;
typedef struct _SugarToolButtonClass SugarToolButtonClass;
typedef struct _SugarToolButtonPrivate SugarToolButtonPrivate;

#define SUGAR_TYPE_TOOLBAR_BUTTON (sugar_toolbar_button_get_type ())
#define SUGAR_TOOLBAR_BUTTON(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SUGAR_TYPE_TOOLBAR_BUTTON, SugarToolbarButton))
#define SUGAR_TOOLBAR_BUTTON_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SUGAR_TYPE_TOOLBAR_BUTTON, SugarToolbarButtonClass))
#define SUGAR_IS_TOOLBAR_BUTTON(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SUGAR_TYPE_TOOLBAR_BUTTON))
#define SUGAR_IS_TOOLBAR_BUTTON_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SUGAR_TYPE_TOOLBAR_BUTTON))
#define SUGAR_TOOLBAR_BUTTON_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SUGAR_TYPE_TOOLBAR_BUTTON, SugarToolbarButtonClass))

typedef struct _SugarToolbarButton SugarToolbarButton;
typedef struct _SugarToolbarButtonClass SugarToolbarButtonClass;
typedef struct _SugarToolbarButtonPrivate SugarToolbarButtonPrivate;

#define SUGAR_TYPE_TOOLBAR_BOX (sugar_toolbar_box_get_type ())
#define SUGAR_TOOLBAR_BOX(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SUGAR_TYPE_TOOLBAR_BOX, SugarToolbarBox))
#define SUGAR_TOOLBAR_BOX_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SUGAR_TYPE_TOOLBAR_BOX, SugarToolbarBoxClass))
#define SUGAR_IS_TOOLBAR_BOX(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SUGAR_TYPE_TOOLBAR_BOX))
#define SUGAR_IS_TOOLBAR_BOX_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SUGAR_TYPE_TOOLBAR_BOX))
#define SUGAR_TOOLBAR_BOX_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SUGAR_TYPE_TOOLBAR_BOX, SugarToolbarBoxClass))

typedef struct _SugarToolbarBox SugarToolbarBox;
typedef struct _SugarToolbarBoxClass SugarToolbarBoxClass;
typedef struct _SugarToolbarBoxPrivate SugarToolbarBoxPrivate;

#define SUGAR_TYPE__TOOLBAREXPANDER (sugar__toolbarexpander_get_type ())
#define SUGAR__TOOLBAREXPANDER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SUGAR_TYPE__TOOLBAREXPANDER, Sugar_ToolbarExpander))
#define SUGAR__TOOLBAREXPANDER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SUGAR_TYPE__TOOLBAREXPANDER, Sugar_ToolbarExpanderClass))
#define SUGAR_IS__TOOLBAREXPANDER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SUGAR_TYPE__TOOLBAREXPANDER))
#define SUGAR_IS__TOOLBAREXPANDER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SUGAR_TYPE__TOOLBAREXPANDER))
#define SUGAR__TOOLBAREXPANDER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SUGAR_TYPE__TOOLBAREXPANDER, Sugar_ToolbarExpanderClass))

typedef struct _Sugar_ToolbarExpander Sugar_ToolbarExpander;
typedef struct _Sugar_ToolbarExpanderClass Sugar_ToolbarExpanderClass;
typedef struct _Sugar_ToolbarExpanderPrivate Sugar_ToolbarExpanderPrivate;

#define SUGAR_TYPE_ANIMATION_TYPE (sugar_animation_type_get_type ())

#define SUGAR_TYPE_ANIMATOR (sugar_animator_get_type ())
#define SUGAR_ANIMATOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SUGAR_TYPE_ANIMATOR, SugarAnimator))
#define SUGAR_ANIMATOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SUGAR_TYPE_ANIMATOR, SugarAnimatorClass))
#define SUGAR_IS_ANIMATOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SUGAR_TYPE_ANIMATOR))
#define SUGAR_IS_ANIMATOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SUGAR_TYPE_ANIMATOR))
#define SUGAR_ANIMATOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SUGAR_TYPE_ANIMATOR, SugarAnimatorClass))

typedef struct _SugarAnimator SugarAnimator;
typedef struct _SugarAnimatorClass SugarAnimatorClass;
typedef struct _SugarAnimatorPrivate SugarAnimatorPrivate;

#define SUGAR_TYPE_MOUSE_SPEED_DETECTOR (sugar_mouse_speed_detector_get_type ())
#define SUGAR_MOUSE_SPEED_DETECTOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SUGAR_TYPE_MOUSE_SPEED_DETECTOR, SugarMouseSpeedDetector))
#define SUGAR_MOUSE_SPEED_DETECTOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SUGAR_TYPE_MOUSE_SPEED_DETECTOR, SugarMouseSpeedDetectorClass))
#define SUGAR_IS_MOUSE_SPEED_DETECTOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SUGAR_TYPE_MOUSE_SPEED_DETECTOR))
#define SUGAR_IS_MOUSE_SPEED_DETECTOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SUGAR_TYPE_MOUSE_SPEED_DETECTOR))
#define SUGAR_MOUSE_SPEED_DETECTOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SUGAR_TYPE_MOUSE_SPEED_DETECTOR, SugarMouseSpeedDetectorClass))

typedef struct _SugarMouseSpeedDetector SugarMouseSpeedDetector;
typedef struct _SugarMouseSpeedDetectorClass SugarMouseSpeedDetectorClass;
typedef struct _SugarMouseSpeedDetectorPrivate SugarMouseSpeedDetectorPrivate;

#define SUGAR_TYPE_PALETTE_GROUP (sugar_palette_group_get_type ())
#define SUGAR_PALETTE_GROUP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SUGAR_TYPE_PALETTE_GROUP, SugarPaletteGroup))
#define SUGAR_PALETTE_GROUP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SUGAR_TYPE_PALETTE_GROUP, SugarPaletteGroupClass))
#define SUGAR_IS_PALETTE_GROUP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SUGAR_TYPE_PALETTE_GROUP))
#define SUGAR_IS_PALETTE_GROUP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SUGAR_TYPE_PALETTE_GROUP))
#define SUGAR_PALETTE_GROUP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SUGAR_TYPE_PALETTE_GROUP, SugarPaletteGroupClass))

typedef struct _SugarPaletteGroup SugarPaletteGroup;
typedef struct _SugarPaletteGroupClass SugarPaletteGroupClass;
typedef struct _SugarPaletteGroupPrivate SugarPaletteGroupPrivate;

#define SUGAR_TYPE_INVOKER (sugar_invoker_get_type ())
#define SUGAR_INVOKER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SUGAR_TYPE_INVOKER, SugarInvoker))
#define SUGAR_INVOKER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SUGAR_TYPE_INVOKER, SugarInvokerClass))
#define SUGAR_IS_INVOKER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SUGAR_TYPE_INVOKER))
#define SUGAR_IS_INVOKER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SUGAR_TYPE_INVOKER))
#define SUGAR_INVOKER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SUGAR_TYPE_INVOKER, SugarInvokerClass))

typedef struct _SugarInvoker SugarInvoker;
typedef struct _SugarInvokerClass SugarInvokerClass;
typedef struct _SugarInvokerPrivate SugarInvokerPrivate;

#define SUGAR_TYPE_CONNECTOR (sugar_connector_get_type ())
#define SUGAR_CONNECTOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SUGAR_TYPE_CONNECTOR, SugarConnector))
#define SUGAR_CONNECTOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SUGAR_TYPE_CONNECTOR, SugarConnectorClass))
#define SUGAR_IS_CONNECTOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SUGAR_TYPE_CONNECTOR))
#define SUGAR_IS_CONNECTOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SUGAR_TYPE_CONNECTOR))
#define SUGAR_CONNECTOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SUGAR_TYPE_CONNECTOR, SugarConnectorClass))

typedef struct _SugarConnector SugarConnector;
typedef struct _SugarConnectorClass SugarConnectorClass;

#define SUGAR_TYPE_PALETTE_WINDOW (sugar_palette_window_get_type ())
#define SUGAR_PALETTE_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SUGAR_TYPE_PALETTE_WINDOW, SugarPaletteWindow))
#define SUGAR_PALETTE_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SUGAR_TYPE_PALETTE_WINDOW, SugarPaletteWindowClass))
#define SUGAR_IS_PALETTE_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SUGAR_TYPE_PALETTE_WINDOW))
#define SUGAR_IS_PALETTE_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SUGAR_TYPE_PALETTE_WINDOW))
#define SUGAR_PALETTE_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SUGAR_TYPE_PALETTE_WINDOW, SugarPaletteWindowClass))

typedef struct _SugarPaletteWindow SugarPaletteWindow;
typedef struct _SugarPaletteWindowClass SugarPaletteWindowClass;

#define SUGAR_TYPE_PALETTE (sugar_palette_get_type ())
#define SUGAR_PALETTE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SUGAR_TYPE_PALETTE, SugarPalette))
#define SUGAR_PALETTE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SUGAR_TYPE_PALETTE, SugarPaletteClass))
#define SUGAR_IS_PALETTE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SUGAR_TYPE_PALETTE))
#define SUGAR_IS_PALETTE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SUGAR_TYPE_PALETTE))
#define SUGAR_PALETTE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SUGAR_TYPE_PALETTE, SugarPaletteClass))

typedef struct _SugarPalette SugarPalette;
typedef struct _SugarPaletteClass SugarPaletteClass;
typedef struct _SugarPaletteWindowPrivate SugarPaletteWindowPrivate;

#define SUGAR_TYPE_ICON (sugar_icon_get_type ())
#define SUGAR_ICON(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SUGAR_TYPE_ICON, SugarIcon))
#define SUGAR_ICON_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SUGAR_TYPE_ICON, SugarIconClass))
#define SUGAR_IS_ICON(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SUGAR_TYPE_ICON))
#define SUGAR_IS_ICON_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SUGAR_TYPE_ICON))
#define SUGAR_ICON_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SUGAR_TYPE_ICON, SugarIconClass))

typedef struct _SugarIcon SugarIcon;
typedef struct _SugarIconClass SugarIconClass;
typedef struct _SugarIconPrivate SugarIconPrivate;

#define SUGAR_TYPE_ICON_ATTR (sugar_icon_attr_get_type ())
typedef struct _SugarIconAttr SugarIconAttr;

#define SUGAR_TYPE_MENU_CONTAINER (sugar_menu_container_get_type ())
#define SUGAR_MENU_CONTAINER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SUGAR_TYPE_MENU_CONTAINER, SugarMenuContainer))
#define SUGAR_IS_MENU_CONTAINER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SUGAR_TYPE_MENU_CONTAINER))
#define SUGAR_MENU_CONTAINER_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), SUGAR_TYPE_MENU_CONTAINER, SugarMenuContainerIface))

typedef struct _SugarMenuContainer SugarMenuContainer;
typedef struct _SugarMenuContainerIface SugarMenuContainerIface;
typedef struct _SugarPalettePrivate SugarPalettePrivate;

#define SUGAR_TYPE_PALETTE_POSITION (sugar_palette_position_get_type ())
typedef struct _SugarConnectorPrivate SugarConnectorPrivate;

#define SUGAR_CONNECTOR_TYPE_ALIGNMENT (sugar_connector_alignment_get_type ())
typedef struct _SugarConnectorAlignment SugarConnectorAlignment;

#define SUGAR_TYPE_WIDGET_CONNECTOR (sugar_widget_connector_get_type ())
#define SUGAR_WIDGET_CONNECTOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SUGAR_TYPE_WIDGET_CONNECTOR, SugarWidgetConnector))
#define SUGAR_WIDGET_CONNECTOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SUGAR_TYPE_WIDGET_CONNECTOR, SugarWidgetConnectorClass))
#define SUGAR_IS_WIDGET_CONNECTOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SUGAR_TYPE_WIDGET_CONNECTOR))
#define SUGAR_IS_WIDGET_CONNECTOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SUGAR_TYPE_WIDGET_CONNECTOR))
#define SUGAR_WIDGET_CONNECTOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SUGAR_TYPE_WIDGET_CONNECTOR, SugarWidgetConnectorClass))

typedef struct _SugarWidgetConnector SugarWidgetConnector;
typedef struct _SugarWidgetConnectorClass SugarWidgetConnectorClass;
typedef struct _SugarWidgetConnectorPrivate SugarWidgetConnectorPrivate;

#define SUGAR_TYPE_TOOL_CONNECTOR (sugar_tool_connector_get_type ())
#define SUGAR_TOOL_CONNECTOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SUGAR_TYPE_TOOL_CONNECTOR, SugarToolConnector))
#define SUGAR_TOOL_CONNECTOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SUGAR_TYPE_TOOL_CONNECTOR, SugarToolConnectorClass))
#define SUGAR_IS_TOOL_CONNECTOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SUGAR_TYPE_TOOL_CONNECTOR))
#define SUGAR_IS_TOOL_CONNECTOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SUGAR_TYPE_TOOL_CONNECTOR))
#define SUGAR_TOOL_CONNECTOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SUGAR_TYPE_TOOL_CONNECTOR, SugarToolConnectorClass))

typedef struct _SugarToolConnector SugarToolConnector;
typedef struct _SugarToolConnectorClass SugarToolConnectorClass;
typedef struct _SugarToolConnectorPrivate SugarToolConnectorPrivate;

#define SUGAR_TYPE_COMBO_TOOL_BUTTON (sugar_combo_tool_button_get_type ())
#define SUGAR_COMBO_TOOL_BUTTON(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SUGAR_TYPE_COMBO_TOOL_BUTTON, SugarComboToolButton))
#define SUGAR_COMBO_TOOL_BUTTON_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SUGAR_TYPE_COMBO_TOOL_BUTTON, SugarComboToolButtonClass))
#define SUGAR_IS_COMBO_TOOL_BUTTON(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SUGAR_TYPE_COMBO_TOOL_BUTTON))
#define SUGAR_IS_COMBO_TOOL_BUTTON_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SUGAR_TYPE_COMBO_TOOL_BUTTON))
#define SUGAR_COMBO_TOOL_BUTTON_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SUGAR_TYPE_COMBO_TOOL_BUTTON, SugarComboToolButtonClass))

typedef struct _SugarComboToolButton SugarComboToolButton;
typedef struct _SugarComboToolButtonClass SugarComboToolButtonClass;
typedef struct _SugarComboToolButtonPrivate SugarComboToolButtonPrivate;

#define SUGAR_TYPE_TOGGLE_TOOL_BUTTON (sugar_toggle_tool_button_get_type ())
#define SUGAR_TOGGLE_TOOL_BUTTON(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SUGAR_TYPE_TOGGLE_TOOL_BUTTON, SugarToggleToolButton))
#define SUGAR_TOGGLE_TOOL_BUTTON_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SUGAR_TYPE_TOGGLE_TOOL_BUTTON, SugarToggleToolButtonClass))
#define SUGAR_IS_TOGGLE_TOOL_BUTTON(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SUGAR_TYPE_TOGGLE_TOOL_BUTTON))
#define SUGAR_IS_TOGGLE_TOOL_BUTTON_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SUGAR_TYPE_TOGGLE_TOOL_BUTTON))
#define SUGAR_TOGGLE_TOOL_BUTTON_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SUGAR_TYPE_TOGGLE_TOOL_BUTTON, SugarToggleToolButtonClass))

typedef struct _SugarToggleToolButton SugarToggleToolButton;
typedef struct _SugarToggleToolButtonClass SugarToggleToolButtonClass;
typedef struct _SugarToggleToolButtonPrivate SugarToggleToolButtonPrivate;

#define SUGAR_TYPE_RADIO_TOOL_BUTTON (sugar_radio_tool_button_get_type ())
#define SUGAR_RADIO_TOOL_BUTTON(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SUGAR_TYPE_RADIO_TOOL_BUTTON, SugarRadioToolButton))
#define SUGAR_RADIO_TOOL_BUTTON_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SUGAR_TYPE_RADIO_TOOL_BUTTON, SugarRadioToolButtonClass))
#define SUGAR_IS_RADIO_TOOL_BUTTON(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SUGAR_TYPE_RADIO_TOOL_BUTTON))
#define SUGAR_IS_RADIO_TOOL_BUTTON_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SUGAR_TYPE_RADIO_TOOL_BUTTON))
#define SUGAR_RADIO_TOOL_BUTTON_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SUGAR_TYPE_RADIO_TOOL_BUTTON, SugarRadioToolButtonClass))

typedef struct _SugarRadioToolButton SugarRadioToolButton;
typedef struct _SugarRadioToolButtonClass SugarRadioToolButtonClass;
typedef struct _SugarRadioToolButtonPrivate SugarRadioToolButtonPrivate;

#define SUGAR_TYPE_ENTRY (sugar_entry_get_type ())
#define SUGAR_ENTRY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SUGAR_TYPE_ENTRY, SugarEntry))
#define SUGAR_ENTRY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SUGAR_TYPE_ENTRY, SugarEntryClass))
#define SUGAR_IS_ENTRY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SUGAR_TYPE_ENTRY))
#define SUGAR_IS_ENTRY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SUGAR_TYPE_ENTRY))
#define SUGAR_ENTRY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SUGAR_TYPE_ENTRY, SugarEntryClass))

typedef struct _SugarEntry SugarEntry;
typedef struct _SugarEntryClass SugarEntryClass;
typedef struct _SugarEntryPrivate SugarEntryPrivate;

#define SUGAR_TYPE_TABLE (sugar_table_get_type ())
#define SUGAR_TABLE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SUGAR_TYPE_TABLE, SugarTable))
#define SUGAR_TABLE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SUGAR_TYPE_TABLE, SugarTableClass))
#define SUGAR_IS_TABLE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SUGAR_TYPE_TABLE))
#define SUGAR_IS_TABLE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SUGAR_TYPE_TABLE))
#define SUGAR_TABLE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SUGAR_TYPE_TABLE, SugarTableClass))

typedef struct _SugarTable SugarTable;
typedef struct _SugarTableClass SugarTableClass;
typedef struct _SugarTablePrivate SugarTablePrivate;

#define SUGAR_TYPE_WINDOW (sugar_window_get_type ())
#define SUGAR_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SUGAR_TYPE_WINDOW, SugarWindow))
#define SUGAR_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SUGAR_TYPE_WINDOW, SugarWindowClass))
#define SUGAR_IS_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SUGAR_TYPE_WINDOW))
#define SUGAR_IS_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SUGAR_TYPE_WINDOW))
#define SUGAR_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SUGAR_TYPE_WINDOW, SugarWindowClass))

typedef struct _SugarWindow SugarWindow;
typedef struct _SugarWindowClass SugarWindowClass;
typedef struct _SugarWindowPrivate SugarWindowPrivate;

#define SUGAR_TYPE_ACCELERATOR (sugar_accelerator_get_type ())
#define SUGAR_ACCELERATOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SUGAR_TYPE_ACCELERATOR, SugarAccelerator))
#define SUGAR_ACCELERATOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SUGAR_TYPE_ACCELERATOR, SugarAcceleratorClass))
#define SUGAR_IS_ACCELERATOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SUGAR_TYPE_ACCELERATOR))
#define SUGAR_IS_ACCELERATOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SUGAR_TYPE_ACCELERATOR))
#define SUGAR_ACCELERATOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SUGAR_TYPE_ACCELERATOR, SugarAcceleratorClass))

typedef struct _SugarAccelerator SugarAccelerator;
typedef struct _SugarAcceleratorClass SugarAcceleratorClass;
typedef struct _SugarAcceleratorPrivate SugarAcceleratorPrivate;

#define SUGAR_TYPE_EMBEDDED_MENU (sugar_embedded_menu_get_type ())
#define SUGAR_EMBEDDED_MENU(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SUGAR_TYPE_EMBEDDED_MENU, SugarEmbeddedMenu))
#define SUGAR_EMBEDDED_MENU_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SUGAR_TYPE_EMBEDDED_MENU, SugarEmbeddedMenuClass))
#define SUGAR_IS_EMBEDDED_MENU(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SUGAR_TYPE_EMBEDDED_MENU))
#define SUGAR_IS_EMBEDDED_MENU_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SUGAR_TYPE_EMBEDDED_MENU))
#define SUGAR_EMBEDDED_MENU_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SUGAR_TYPE_EMBEDDED_MENU, SugarEmbeddedMenuClass))

typedef struct _SugarEmbeddedMenu SugarEmbeddedMenu;
typedef struct _SugarEmbeddedMenuClass SugarEmbeddedMenuClass;
typedef struct _SugarEmbeddedMenuPrivate SugarEmbeddedMenuPrivate;

#define SUGAR_TYPE_EMBEDDED_SUB_MENU (sugar_embedded_sub_menu_get_type ())
#define SUGAR_EMBEDDED_SUB_MENU(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SUGAR_TYPE_EMBEDDED_SUB_MENU, SugarEmbeddedSubMenu))
#define SUGAR_EMBEDDED_SUB_MENU_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SUGAR_TYPE_EMBEDDED_SUB_MENU, SugarEmbeddedSubMenuClass))
#define SUGAR_IS_EMBEDDED_SUB_MENU(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SUGAR_TYPE_EMBEDDED_SUB_MENU))
#define SUGAR_IS_EMBEDDED_SUB_MENU_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SUGAR_TYPE_EMBEDDED_SUB_MENU))
#define SUGAR_EMBEDDED_SUB_MENU_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SUGAR_TYPE_EMBEDDED_SUB_MENU, SugarEmbeddedSubMenuClass))

typedef struct _SugarEmbeddedSubMenu SugarEmbeddedSubMenu;
typedef struct _SugarEmbeddedSubMenuClass SugarEmbeddedSubMenuClass;
typedef struct _SugarEmbeddedSubMenuPrivate SugarEmbeddedSubMenuPrivate;

#define SUGAR_TYPE__EMBEDDEDMENU (sugar__embeddedmenu_get_type ())
#define SUGAR__EMBEDDEDMENU(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SUGAR_TYPE__EMBEDDEDMENU, Sugar_EmbeddedMenu))
#define SUGAR__EMBEDDEDMENU_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SUGAR_TYPE__EMBEDDEDMENU, Sugar_EmbeddedMenuClass))
#define SUGAR_IS__EMBEDDEDMENU(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SUGAR_TYPE__EMBEDDEDMENU))
#define SUGAR_IS__EMBEDDEDMENU_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SUGAR_TYPE__EMBEDDEDMENU))
#define SUGAR__EMBEDDEDMENU_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SUGAR_TYPE__EMBEDDEDMENU, Sugar_EmbeddedMenuClass))

typedef struct _Sugar_EmbeddedMenu Sugar_EmbeddedMenu;
typedef struct _Sugar_EmbeddedMenuClass Sugar_EmbeddedMenuClass;
typedef struct _Sugar_EmbeddedMenuPrivate Sugar_EmbeddedMenuPrivate;

#define SUGAR_TYPE_MENU_ITEM (sugar_menu_item_get_type ())
#define SUGAR_MENU_ITEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SUGAR_TYPE_MENU_ITEM, SugarMenuItem))
#define SUGAR_MENU_ITEM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SUGAR_TYPE_MENU_ITEM, SugarMenuItemClass))
#define SUGAR_IS_MENU_ITEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SUGAR_TYPE_MENU_ITEM))
#define SUGAR_IS_MENU_ITEM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SUGAR_TYPE_MENU_ITEM))
#define SUGAR_MENU_ITEM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SUGAR_TYPE_MENU_ITEM, SugarMenuItemClass))

typedef struct _SugarMenuItem SugarMenuItem;
typedef struct _SugarMenuItemClass SugarMenuItemClass;
typedef struct _SugarMenuItemPrivate SugarMenuItemPrivate;

#define SUGAR_TYPE_MENU (sugar_menu_get_type ())
#define SUGAR_MENU(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SUGAR_TYPE_MENU, SugarMenu))
#define SUGAR_MENU_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SUGAR_TYPE_MENU, SugarMenuClass))
#define SUGAR_IS_MENU(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SUGAR_TYPE_MENU))
#define SUGAR_IS_MENU_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SUGAR_TYPE_MENU))
#define SUGAR_MENU_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SUGAR_TYPE_MENU, SugarMenuClass))

typedef struct _SugarMenu SugarMenu;
typedef struct _SugarMenuClass SugarMenuClass;
typedef struct _SugarMenuPrivate SugarMenuPrivate;

#define SUGAR_TYPE_LABEL (sugar_label_get_type ())
#define SUGAR_LABEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SUGAR_TYPE_LABEL, SugarLabel))
#define SUGAR_LABEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SUGAR_TYPE_LABEL, SugarLabelClass))
#define SUGAR_IS_LABEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SUGAR_TYPE_LABEL))
#define SUGAR_IS_LABEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SUGAR_TYPE_LABEL))
#define SUGAR_LABEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SUGAR_TYPE_LABEL, SugarLabelClass))

typedef struct _SugarLabel SugarLabel;
typedef struct _SugarLabelClass SugarLabelClass;
typedef struct _SugarLabelPrivate SugarLabelPrivate;

#define SUGAR_TYPE_ALIGNMENT (sugar_alignment_get_type ())
#define SUGAR_ALIGNMENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SUGAR_TYPE_ALIGNMENT, SugarAlignment))
#define SUGAR_ALIGNMENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SUGAR_TYPE_ALIGNMENT, SugarAlignmentClass))
#define SUGAR_IS_ALIGNMENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SUGAR_TYPE_ALIGNMENT))
#define SUGAR_IS_ALIGNMENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SUGAR_TYPE_ALIGNMENT))
#define SUGAR_ALIGNMENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SUGAR_TYPE_ALIGNMENT, SugarAlignmentClass))

typedef struct _SugarAlignment SugarAlignment;
typedef struct _SugarAlignmentClass SugarAlignmentClass;
typedef struct _SugarAlignmentPrivate SugarAlignmentPrivate;

struct _SugarRange {
	gint start;
	gint stop;
	gint step;
};

struct _SugarTimestamp {
	GTimeVal tv;
};

struct _SugarTrigger {
	GObject parent_instance;
	SugarTriggerPrivate * priv;
};

struct _SugarTriggerClass {
	GObjectClass parent_class;
};

struct _SugarContainer {
	GtkContainer parent_instance;
	SugarContainerPrivate * priv;
};

struct _SugarContainerClass {
	GtkContainerClass parent_class;
	void (*child_size_request) (SugarContainer* self, GtkRequisition* req);
	gint (*get_child_x) (SugarContainer* self);
	gint (*get_child_y) (SugarContainer* self);
	gint (*get_child_width) (SugarContainer* self);
	gint (*get_child_height) (SugarContainer* self);
};

struct _SugarBox {
	SugarContainer parent_instance;
	SugarBoxPrivate * priv;
	GList* children;
};

struct _SugarBoxClass {
	SugarContainerClass parent_class;
	void (*insert) (SugarBox* self, GtkWidget* widget, gint pos);
};

struct _SugarBin {
	SugarContainer parent_instance;
	SugarBinPrivate * priv;
};

struct _SugarBinClass {
	SugarContainerClass parent_class;
};

struct _SugarPaintBin {
	SugarBin parent_instance;
	SugarPaintBinPrivate * priv;
};

struct _SugarPaintBinClass {
	SugarBinClass parent_class;
};

struct _SugarToolText {
	GtkToolItem parent_instance;
	SugarToolTextPrivate * priv;
};

struct _SugarToolTextClass {
	GtkToolItemClass parent_class;
};

struct _SugarHomogeneTable {
	SugarContainer parent_instance;
	SugarHomogeneTablePrivate * priv;
};

struct _SugarHomogeneTableClass {
	SugarContainerClass parent_class;
	GtkWidget* (*new_cell) (SugarHomogeneTable* self);
	void (*fill_cell) (SugarHomogeneTable* self, GtkWidget* cell, gint index);
	void (*highlight_cell) (SugarHomogeneTable* self, GtkWidget* cell, gboolean selected);
	void (*signal_set_scroll_adjustments) (SugarHomogeneTable* self, GtkAdjustment* hadjustment, GtkAdjustment* vadjustment);
};

struct _SugarToolButton {
	GtkToolButton parent_instance;
	SugarToolButtonPrivate * priv;
};

struct _SugarToolButtonClass {
	GtkToolButtonClass parent_class;
};

struct _SugarToolbarButton {
	SugarToolButton parent_instance;
	SugarToolbarButtonPrivate * priv;
};

struct _SugarToolbarButtonClass {
	SugarToolButtonClass parent_class;
};

struct _SugarToolbarBox {
	GtkVBox parent_instance;
	SugarToolbarBoxPrivate * priv;
};

struct _SugarToolbarBoxClass {
	GtkVBoxClass parent_class;
};

struct _Sugar_ToolbarExpander {
	GtkToolbar parent_instance;
	Sugar_ToolbarExpanderPrivate * priv;
};

struct _Sugar_ToolbarExpanderClass {
	GtkToolbarClass parent_class;
};

typedef enum  {
	SUGAR_ANIMATION_TYPE_OUT_EXPO,
	SUGAR_ANIMATION_TYPE_IN_EXPO
} SugarAnimationType;

struct _SugarAnimator {
	GObject parent_instance;
	SugarAnimatorPrivate * priv;
};

struct _SugarAnimatorClass {
	GObjectClass parent_class;
};

struct _SugarMouseSpeedDetector {
	GObject parent_instance;
	SugarMouseSpeedDetectorPrivate * priv;
};

struct _SugarMouseSpeedDetectorClass {
	GObjectClass parent_class;
};

struct _SugarPaletteGroup {
	GObject parent_instance;
	SugarPaletteGroupPrivate * priv;
};

struct _SugarPaletteGroupClass {
	GObjectClass parent_class;
};

struct _SugarInvoker {
	GObject parent_instance;
	SugarInvokerPrivate * priv;
};

struct _SugarInvokerClass {
	GObjectClass parent_class;
};

struct _SugarPaletteWindow {
	GtkWindow parent_instance;
	SugarPaletteWindowPrivate * priv;
};

struct _SugarPaletteWindowClass {
	GtkWindowClass parent_class;
	GtkWidget* (*get_secondary) (SugarPaletteWindow* self);
	void (*set_secondary) (SugarPaletteWindow* self, GtkWidget* value);
	gboolean (*get_secondary_visible) (SugarPaletteWindow* self);
	void (*set_secondary_visible) (SugarPaletteWindow* self, gboolean value);
};

struct _SugarIcon {
	GtkImage parent_instance;
	SugarIconPrivate * priv;
};

struct _SugarIconClass {
	GtkImageClass parent_class;
};

struct _SugarIconAttr {
	char* file_name;
	SugarColor fill_color;
	SugarColor stroke_color;
	gint width;
	gint height;
};

struct _SugarMenuContainerIface {
	GTypeInterface parent_iface;
	SugarTrigger* (*get_menu_trigger) (SugarMenuContainer* self);
};

struct _SugarPalette {
	SugarPaletteWindow parent_instance;
	SugarPalettePrivate * priv;
};

struct _SugarPaletteClass {
	SugarPaletteWindowClass parent_class;
};

typedef enum  {
	SUGAR_PALETTE_POSITION_ANCHORED,
	SUGAR_PALETTE_POSITION_AT_CURSOR
} SugarPalettePosition;

struct _SugarConnectorAlignment {
	float palette_halign;
	float palette_valign;
	float invoker_halign;
	float invoker_valign;
	gint position;
};

struct _SugarConnector {
	GObject parent_instance;
	SugarConnectorPrivate * priv;
};

struct _SugarConnectorClass {
	GObjectClass parent_class;
	void (*on_popup) (SugarConnector* self);
	void (*on_popdown) (SugarConnector* self);
	void (*draw_rectangle) (SugarConnector* self, GdkEventExpose* event, SugarPaletteWindow* palette);
	GtkWindow* (*get_toplevel) (SugarConnector* self);
	void (*get_rect) (SugarConnector* self, GdkRectangle* result);
	SugarConnectorAlignment* (*get_alignments) (SugarConnector* self, int* result_length1);
};

struct _SugarWidgetConnector {
	SugarConnector parent_instance;
	SugarWidgetConnectorPrivate * priv;
};

struct _SugarWidgetConnectorClass {
	SugarConnectorClass parent_class;
};

struct _SugarToolConnector {
	SugarWidgetConnector parent_instance;
	SugarToolConnectorPrivate * priv;
};

struct _SugarToolConnectorClass {
	SugarWidgetConnectorClass parent_class;
};

struct _SugarComboToolButton {
	SugarToolButton parent_instance;
	SugarComboToolButtonPrivate * priv;
};

struct _SugarComboToolButtonClass {
	SugarToolButtonClass parent_class;
};

struct _SugarToggleToolButton {
	GtkToggleToolButton parent_instance;
	SugarToggleToolButtonPrivate * priv;
};

struct _SugarToggleToolButtonClass {
	GtkToggleToolButtonClass parent_class;
};

struct _SugarRadioToolButton {
	GtkRadioToolButton parent_instance;
	SugarRadioToolButtonPrivate * priv;
};

struct _SugarRadioToolButtonClass {
	GtkRadioToolButtonClass parent_class;
};

struct _SugarEntry {
	GtkEntry parent_instance;
	SugarEntryPrivate * priv;
};

struct _SugarEntryClass {
	GtkEntryClass parent_class;
};

struct _SugarTable {
	SugarBox parent_instance;
	SugarTablePrivate * priv;
};

struct _SugarTableClass {
	SugarBoxClass parent_class;
};

struct _SugarWindow {
	GtkWindow parent_instance;
	SugarWindowPrivate * priv;
};

struct _SugarWindowClass {
	GtkWindowClass parent_class;
};

struct _SugarAccelerator {
	GTypeInstance parent_instance;
	volatile int ref_count;
	SugarAcceleratorPrivate * priv;
};

struct _SugarAcceleratorClass {
	GTypeClass parent_class;
	void (*finalize) (SugarAccelerator *self);
};

struct _SugarEmbeddedMenu {
	SugarBin parent_instance;
	SugarEmbeddedMenuPrivate * priv;
};

struct _SugarEmbeddedMenuClass {
	SugarBinClass parent_class;
};

struct _SugarEmbeddedSubMenu {
	GtkMenu parent_instance;
	SugarEmbeddedSubMenuPrivate * priv;
};

struct _SugarEmbeddedSubMenuClass {
	GtkMenuClass parent_class;
};

struct _Sugar_EmbeddedMenu {
	GtkMenu parent_instance;
	Sugar_EmbeddedMenuPrivate * priv;
};

struct _Sugar_EmbeddedMenuClass {
	GtkMenuClass parent_class;
};

struct _SugarMenuItem {
	SugarPaintBin parent_instance;
	SugarMenuItemPrivate * priv;
};

struct _SugarMenuItemClass {
	SugarPaintBinClass parent_class;
	void (*activate_item) (SugarMenuItem* self);
};

struct _SugarMenu {
	SugarBox parent_instance;
	SugarMenuPrivate * priv;
};

struct _SugarMenuClass {
	SugarBoxClass parent_class;
};

struct _SugarLabel {
	GtkLabel parent_instance;
	SugarLabelPrivate * priv;
};

struct _SugarLabelClass {
	GtkLabelClass parent_class;
};

struct _SugarAlignment {
	SugarBin parent_instance;
	SugarAlignmentPrivate * priv;
};

struct _SugarAlignmentClass {
	SugarBinClass parent_class;
};


GType sugar_range_get_type (void) G_GNUC_CONST;
SugarRange* sugar_range_dup (const SugarRange* self);
void sugar_range_free (SugarRange* self);
void sugar_range_init (SugarRange *self);
gboolean sugar_range_contains (SugarRange *self, gint value);
gboolean sugar_range_is_equal (SugarRange *self, SugarRange* other);
gboolean sugar_range_is_subset (SugarRange *self, SugarRange* other);
gint sugar_range_get_last (SugarRange* self);
void sugar_range_set_last (SugarRange* self, gint value);
gint sugar_range_get_size (SugarRange* self);
gboolean sugar_range_get_is_empty (SugarRange* self);
GType sugar_timestamp_get_type (void) G_GNUC_CONST;
SugarTimestamp* sugar_timestamp_dup (const SugarTimestamp* self);
void sugar_timestamp_free (SugarTimestamp* self);
void sugar_timestamp_init (SugarTimestamp *self);
double sugar_timestamp_diff (SugarTimestamp *self, SugarTimestamp* other);
const char* sugar_to_string (gchar* str);
guchar* sugar_to_uchars (gchar* str, int* result_length1);
GType sugar_trigger_get_type (void) G_GNUC_CONST;
SugarTrigger* sugar_trigger_find_dock (GType parent_type, GtkWidget* parent, const char* prop_name);
SugarTrigger* sugar_trigger_new (void);
SugarTrigger* sugar_trigger_construct (GType object_type);
void sugar_color_type_to_rgb (gint type, GdkColor* result);
void sugar_color_to_rgb (SugarColor* color, GdkColor* result);
GArray* sugar_get_preview (void);
GType sugar_container_get_type (void) G_GNUC_CONST;
void sugar_container_clear (SugarContainer* self);
void sugar_container_get_pointer (SugarContainer* self, gint* x, gint* y);
void sugar_container_child_size_request (SugarContainer* self, GtkRequisition* req);
SugarContainer* sugar_container_new (void);
SugarContainer* sugar_container_construct (GType object_type);
gint sugar_container_get_border_left (SugarContainer* self);
void sugar_container_set_border_left (SugarContainer* self, gint value);
gint sugar_container_get_border_right (SugarContainer* self);
void sugar_container_set_border_right (SugarContainer* self, gint value);
gint sugar_container_get_border_top (SugarContainer* self);
void sugar_container_set_border_top (SugarContainer* self, gint value);
gint sugar_container_get_border_bottom (SugarContainer* self);
void sugar_container_set_border_bottom (SugarContainer* self, gint value);
void sugar_container_set_border (SugarContainer* self, gint value);
gint sugar_container_get_child_x (SugarContainer* self);
gint sugar_container_get_child_y (SugarContainer* self);
gint sugar_container_get_child_width (SugarContainer* self);
gint sugar_container_get_child_height (SugarContainer* self);
GType sugar_box_get_type (void) G_GNUC_CONST;
SugarBox* sugar_box_new (void);
SugarBox* sugar_box_construct (GType object_type);
gint sugar_box_get_children_count (SugarBox* self);
void sugar_box_insert (SugarBox* self, GtkWidget* widget, gint pos);
GType sugar_bin_get_type (void) G_GNUC_CONST;
SugarBin* sugar_bin_new (void);
SugarBin* sugar_bin_construct (GType object_type);
GtkWidget* sugar_bin_get_child (SugarBin* self);
void sugar_bin_set_child (SugarBin* self, GtkWidget* value);
GType sugar_paint_bin_get_type (void) G_GNUC_CONST;
SugarPaintBin* sugar_paint_bin_new (void);
SugarPaintBin* sugar_paint_bin_construct (GType object_type);
gboolean sugar_paint_bin_get_draw_box (SugarPaintBin* self);
void sugar_paint_bin_set_draw_box (SugarPaintBin* self, gboolean value);
gint sugar_paint_bin_get_radius (SugarPaintBin* self);
void sugar_paint_bin_set_radius (SugarPaintBin* self, gint value);
gint sugar_paint_bin_get_padding_top (SugarPaintBin* self);
void sugar_paint_bin_set_padding_top (SugarPaintBin* self, gint value);
gint sugar_paint_bin_get_padding_bottom (SugarPaintBin* self);
void sugar_paint_bin_set_padding_bottom (SugarPaintBin* self, gint value);
gint sugar_paint_bin_get_padding_left (SugarPaintBin* self);
void sugar_paint_bin_set_padding_left (SugarPaintBin* self, gint value);
gint sugar_paint_bin_get_padding_right (SugarPaintBin* self);
void sugar_paint_bin_set_padding_right (SugarPaintBin* self, gint value);
void sugar_paint_bin_set_padding (SugarPaintBin* self, gint value);
GType sugar_tool_text_get_type (void) G_GNUC_CONST;
SugarToolText* sugar_tool_text_new (void);
SugarToolText* sugar_tool_text_construct (GType object_type);
const char* sugar_tool_text_get_text (SugarToolText* self);
void sugar_tool_text_set_text (SugarToolText* self, const char* value);
GType sugar_homogene_table_get_type (void) G_GNUC_CONST;
GtkWidget* sugar_homogene_table_new_cell (SugarHomogeneTable* self);
void sugar_homogene_table_fill_cell (SugarHomogeneTable* self, GtkWidget* cell, gint index);
void sugar_homogene_table_highlight_cell (SugarHomogeneTable* self, GtkWidget* cell, gboolean selected);
GtkWidget* sugar_homogene_table_get_cell (SugarHomogeneTable* self, gint cell_index);
gint sugar_homogene_table_get_index_at_pos (SugarHomogeneTable* self, gint x, gint y);
void sugar_homogene_table_scroll_to_cell (SugarHomogeneTable* self, gint cell_index, gboolean fully_visible);
void sugar_homogene_table_refill (SugarHomogeneTable* self);
SugarHomogeneTable* sugar_homogene_table_construct (GType object_type);
gint sugar_homogene_table_get_cell_count (SugarHomogeneTable* self);
void sugar_homogene_table_set_cell_count (SugarHomogeneTable* self, gint value);
gint sugar_homogene_table_get_frame_width (SugarHomogeneTable* self);
void sugar_homogene_table_set_frame_width (SugarHomogeneTable* self, gint value);
gint sugar_homogene_table_get_frame_height (SugarHomogeneTable* self);
void sugar_homogene_table_set_frame_height (SugarHomogeneTable* self, gint value);
gint sugar_homogene_table_get_cell_width (SugarHomogeneTable* self);
void sugar_homogene_table_set_cell_width (SugarHomogeneTable* self, gint value);
gint sugar_homogene_table_get_cell_height (SugarHomogeneTable* self);
void sugar_homogene_table_set_cell_height (SugarHomogeneTable* self, gint value);
GtkOrientation sugar_homogene_table_get_orientation (SugarHomogeneTable* self);
void sugar_homogene_table_set_orientation (SugarHomogeneTable* self, GtkOrientation value);
gboolean sugar_homogene_table_get_hover_selection (SugarHomogeneTable* self);
void sugar_homogene_table_set_hover_selection (SugarHomogeneTable* self, gboolean value);
gint sugar_homogene_table_get_cursor (SugarHomogeneTable* self);
void sugar_homogene_table_set_cursor (SugarHomogeneTable* self, gint value);
gboolean sugar_homogene_table_get_focus_cell (SugarHomogeneTable* self);
void sugar_homogene_table_set_focus_cell (SugarHomogeneTable* self, gboolean value);
void sugar_homogene_table_get_frame_range (SugarHomogeneTable* self, SugarRange* result);
void sugar_homogene_table_set_frame_range (SugarHomogeneTable* self, SugarRange* value);
gboolean sugar_homogene_table_get_is_empty (SugarHomogeneTable* self);
void sugar_homogene_table_signal_set_scroll_adjustments (SugarHomogeneTable* self, GtkAdjustment* hadjustment, GtkAdjustment* vadjustment);
GType sugar_tool_button_get_type (void) G_GNUC_CONST;
GType sugar_toolbar_button_get_type (void) G_GNUC_CONST;
SugarToolbarButton* sugar_toolbar_button_new (void);
SugarToolbarButton* sugar_toolbar_button_construct (GType object_type);
GtkWidget* sugar_toolbar_button_get_page (SugarToolbarButton* self);
void sugar_toolbar_button_set_page (SugarToolbarButton* self, GtkWidget* value);
gboolean sugar_toolbar_button_get_popped (SugarToolbarButton* self);
void sugar_toolbar_button_set_popped (SugarToolbarButton* self, gboolean value);
gboolean sugar_toolbar_button_get_expanded (SugarToolbarButton* self);
void sugar_toolbar_button_set_expanded (SugarToolbarButton* self, gboolean value);
GType sugar_toolbar_box_get_type (void) G_GNUC_CONST;
void sugar_toolbar_box_expand_button (SugarToolbarBox* self, SugarToolbarButton* button);
void sugar_toolbar_box_shrink_button (SugarToolbarBox* self, SugarToolbarButton* button);
SugarToolbarBox* sugar_toolbar_box_new (void);
SugarToolbarBox* sugar_toolbar_box_construct (GType object_type);
GType sugar__toolbarexpander_get_type (void) G_GNUC_CONST;
Sugar_ToolbarExpander* sugar_toolbar_box_get_toolbar (SugarToolbarBox* self);
GtkPositionType sugar_toolbar_box_get_orientation (SugarToolbarBox* self);
void sugar_toolbar_box_set_orientation (SugarToolbarBox* self, GtkPositionType value);
gint sugar_toolbar_box_get_padding (SugarToolbarBox* self);
void sugar_toolbar_box_set_padding (SugarToolbarBox* self, gint value);
Sugar_ToolbarExpander* sugar__toolbarexpander_new (void);
Sugar_ToolbarExpander* sugar__toolbarexpander_construct (GType object_type);
SugarToolbarBox* sugar__toolbarexpander_get_toolbox (Sugar_ToolbarExpander* self);
GType sugar_animation_type_get_type (void) G_GNUC_CONST;
GType sugar_animator_get_type (void) G_GNUC_CONST;
SugarAnimator* sugar_animator_new (double duration, gint fps, double start, double stop, SugarAnimationType type);
SugarAnimator* sugar_animator_construct (GType object_type, double duration, gint fps, double start, double stop, SugarAnimationType type);
void sugar_animator_start (SugarAnimator* self);
void sugar_animator_abort (SugarAnimator* self);
gboolean sugar_animator_get_active (SugarAnimator* self);
GType sugar_mouse_speed_detector_get_type (void) G_GNUC_CONST;
SugarMouseSpeedDetector* sugar_mouse_speed_detector_new (gint delay, gint threshold);
SugarMouseSpeedDetector* sugar_mouse_speed_detector_construct (GType object_type, gint delay, gint threshold);
void sugar_mouse_speed_detector_start (SugarMouseSpeedDetector* self);
void sugar_mouse_speed_detector_stop (SugarMouseSpeedDetector* self);
GType sugar_palette_group_get_type (void) G_GNUC_CONST;
SugarPaletteGroup* sugar_palette_groups_get (const char* group_id);
void sugar_palette_groups_popdown_all (void);
GType sugar_invoker_get_type (void) G_GNUC_CONST;
void sugar_palette_group_add (SugarPaletteGroup* self, SugarInvoker* invoker);
void sugar_palette_group_remove (SugarPaletteGroup* self, SugarInvoker* invoker);
void sugar_palette_group_popdown (SugarPaletteGroup* self);
SugarInvoker* sugar_palette_group_get_parent (SugarPaletteGroup* self, SugarInvoker* child);
SugarPaletteGroup* sugar_palette_group_new (void);
SugarPaletteGroup* sugar_palette_group_construct (GType object_type);
const char* sugar_palette_group_get_id (SugarPaletteGroup* self);
void sugar_palette_group_set_id (SugarPaletteGroup* self, const char* value);
gboolean sugar_palette_group_get_is_up (SugarPaletteGroup* self);
GType sugar_connector_get_type (void) G_GNUC_CONST;
SugarInvoker* sugar_invoker_new (SugarConnector* connector, const char* group_id);
SugarInvoker* sugar_invoker_construct (GType object_type, SugarConnector* connector, const char* group_id);
void sugar_invoker_popup (SugarInvoker* self);
void sugar_invoker_popdown (SugarInvoker* self);
SugarConnector* sugar_invoker_get_connector (SugarInvoker* self);
void sugar_invoker_set_connector (SugarInvoker* self, SugarConnector* value);
const char* sugar_invoker_get_group_id (SugarInvoker* self);
void sugar_invoker_set_group_id (SugarInvoker* self, const char* value);
GType sugar_palette_window_get_type (void) G_GNUC_CONST;
SugarPaletteWindow* sugar_invoker_get_palette_window (SugarInvoker* self);
void sugar_invoker_set_palette_window (SugarInvoker* self, SugarPaletteWindow* value);
GType sugar_palette_get_type (void) G_GNUC_CONST;
SugarPalette* sugar_invoker_get_palette (SugarInvoker* self);
void sugar_invoker_set_palette (SugarInvoker* self, SugarPalette* value);
gboolean sugar_invoker_get_is_up (SugarInvoker* self);
gboolean sugar_invoker_get_focused (SugarInvoker* self);
void sugar_palette_window_get_rect (SugarPaletteWindow* self, GdkRectangle* result);
void sugar_palette_window_reveal (SugarPaletteWindow* self);
SugarPaletteWindow* sugar_palette_window_new (void);
SugarPaletteWindow* sugar_palette_window_construct (GType object_type);
SugarConnector* sugar_palette_window_get_connector (SugarPaletteWindow* self);
void sugar_palette_window_set_connector (SugarPaletteWindow* self, SugarConnector* value);
GtkWidget* sugar_palette_window_get_secondary (SugarPaletteWindow* self);
void sugar_palette_window_set_secondary (SugarPaletteWindow* self, GtkWidget* value);
gboolean sugar_palette_window_get_secondary_visible (SugarPaletteWindow* self);
void sugar_palette_window_set_secondary_visible (SugarPaletteWindow* self, gboolean value);
GType sugar_icon_get_type (void) G_GNUC_CONST;
SugarIcon* sugar_icon_new (void);
SugarIcon* sugar_icon_construct (GType object_type);
const char* sugar_icon_get_file (SugarIcon* self);
void sugar_icon_set_file (SugarIcon* self, const char* value);
void sugar_icon_get_fill_color (SugarIcon* self, SugarColor* result);
void sugar_icon_set_fill_color (SugarIcon* self, SugarColor* value);
void sugar_icon_get_stroke_color (SugarIcon* self, SugarColor* result);
void sugar_icon_set_stroke_color (SugarIcon* self, SugarColor* value);
void sugar_icon_set_xo_color (SugarIcon* self, SugarXoColor* value);
gint sugar_icon_get_width (SugarIcon* self);
gint sugar_icon_get_height (SugarIcon* self);
void sugar_icon_set_pixel_size (SugarIcon* self, gint value);
void sugar_icon_set_icon_size (SugarIcon* self, GtkIconSize value);
gboolean sugar_icon_get_pulsing (SugarIcon* self);
void sugar_icon_set_pulsing (SugarIcon* self, gboolean value);
GType sugar_icon_attr_get_type (void) G_GNUC_CONST;
SugarIconAttr* sugar_icon_attr_dup (const SugarIconAttr* self);
void sugar_icon_attr_free (SugarIconAttr* self);
void sugar_icon_attr_copy (const SugarIconAttr* self, SugarIconAttr* dest);
void sugar_icon_attr_destroy (SugarIconAttr* self);
guint sugar_icon_attr_hash (SugarIconAttr* x);
gboolean sugar_icon_attr_cmp (SugarIconAttr* x, SugarIconAttr* y);
void sugar_icon_attr_set_xo_color (SugarIconAttr* self, SugarXoColor* value);
void sugar_icon_attr_set_icon_name (SugarIconAttr* self, const char* value);
void sugar_icon_attr_set_icon_size (SugarIconAttr* self, GtkIconSize value);
void sugar_icon_cache_reset (void);
cairo_surface_t* sugar_icon_get_surface (SugarIconAttr* attr, gboolean cache);
GdkPixbuf* sugar_icon_get_pixbuf (SugarIconAttr* attr);
GType sugar_menu_container_get_type (void) G_GNUC_CONST;
SugarPalette* sugar_palette_new (void);
SugarPalette* sugar_palette_construct (GType object_type);
const char* sugar_palette_get_primary_text (SugarPalette* self);
void sugar_palette_set_primary_text (SugarPalette* self, const char* value);
const char* sugar_palette_get_secondary_text (SugarPalette* self);
void sugar_palette_set_secondary_text (SugarPalette* self, const char* value);
void sugar_palette_set_text_maxlen (SugarPalette* self, gint value);
SugarIcon* sugar_palette_get_icon (SugarPalette* self);
void sugar_palette_set_icon (SugarPalette* self, SugarIcon* value);
gboolean sugar_palette_get_icon_visible (SugarPalette* self);
void sugar_palette_set_icon_visible (SugarPalette* self, gboolean value);
GType sugar_palette_position_get_type (void) G_GNUC_CONST;
GType sugar_connector_alignment_get_type (void) G_GNUC_CONST;
SugarConnectorAlignment* sugar_connector_alignment_dup (const SugarConnectorAlignment* self);
void sugar_connector_alignment_free (SugarConnectorAlignment* self);
gboolean sugar_connector_get_box_gap (GdkRectangle* a, GdkRectangle* b, GtkPositionType* gap_side, gint* gap_start, gint* gap_size);
void sugar_connector_get_palette_pos (SugarConnector* self, GtkRequisition* palette_size, gint* x, gint* y);
void sugar_connector_on_popup (SugarConnector* self);
void sugar_connector_on_popdown (SugarConnector* self);
void sugar_connector_draw_rectangle (SugarConnector* self, GdkEventExpose* event, SugarPaletteWindow* palette);
GtkWindow* sugar_connector_get_toplevel (SugarConnector* self);
void sugar_connector_get_rect (SugarConnector* self, GdkRectangle* result);
SugarConnectorAlignment* sugar_connector_get_alignments (SugarConnector* self, int* result_length1);
SugarConnector* sugar_connector_construct (GType object_type);
GObject* sugar_connector_get_subject (SugarConnector* self);
void sugar_connector_set_subject (SugarConnector* self, GObject* value);
SugarPalettePosition sugar_connector_get_palette_position (SugarConnector* self);
void sugar_connector_set_palette_position (SugarConnector* self, SugarPalettePosition value);
GType sugar_widget_connector_get_type (void) G_GNUC_CONST;
SugarWidgetConnector* sugar_widget_connector_new (GtkWidget* widget);
SugarWidgetConnector* sugar_widget_connector_construct (GType object_type, GtkWidget* widget);
GtkWidget* sugar_widget_connector_get_widget (SugarWidgetConnector* self);
void sugar_widget_connector_set_widget (SugarWidgetConnector* self, GtkWidget* value);
GType sugar_tool_connector_get_type (void) G_GNUC_CONST;
SugarToolConnector* sugar_tool_connector_new (GtkToolItem* tool_item);
SugarToolConnector* sugar_tool_connector_construct (GType object_type, GtkToolItem* tool_item);
GtkToolItem* sugar_tool_connector_get_tool_item (SugarToolConnector* self);
void sugar_tool_connector_set_tool_item (SugarToolConnector* self, GtkToolItem* value);
SugarToolButton* sugar_tool_button_new (void);
SugarToolButton* sugar_tool_button_construct (GType object_type);
SugarInvoker* sugar_tool_button_get_invoker (SugarToolButton* self);
const char* sugar_tool_button_get_tooltip (SugarToolButton* self);
void sugar_tool_button_set_tooltip (SugarToolButton* self, const char* value);
const char* sugar_tool_button_get_accelerator (SugarToolButton* self);
void sugar_tool_button_set_accelerator (SugarToolButton* self, const char* value);
void sugar_tool_button_set_icon_name (SugarToolButton* self, const char* value);
SugarIcon* sugar_tool_button_get_icon (SugarToolButton* self);
GType sugar_combo_tool_button_get_type (void) G_GNUC_CONST;
SugarComboToolButton* sugar_combo_tool_button_new (void);
SugarComboToolButton* sugar_combo_tool_button_construct (GType object_type);
GtkRadioAction* sugar_combo_tool_button_get_action (SugarComboToolButton* self);
void sugar_combo_tool_button_set_action (SugarComboToolButton* self, GtkRadioAction* value);
GType sugar_toggle_tool_button_get_type (void) G_GNUC_CONST;
SugarToggleToolButton* sugar_toggle_tool_button_new (void);
SugarToggleToolButton* sugar_toggle_tool_button_construct (GType object_type);
SugarInvoker* sugar_toggle_tool_button_get_invoker (SugarToggleToolButton* self);
const char* sugar_toggle_tool_button_get_tooltip (SugarToggleToolButton* self);
void sugar_toggle_tool_button_set_tooltip (SugarToggleToolButton* self, const char* value);
const char* sugar_toggle_tool_button_get_accelerator (SugarToggleToolButton* self);
void sugar_toggle_tool_button_set_accelerator (SugarToggleToolButton* self, const char* value);
void sugar_toggle_tool_button_set_icon_name (SugarToggleToolButton* self, const char* value);
SugarIcon* sugar_toggle_tool_button_get_icon (SugarToggleToolButton* self);
GType sugar_radio_tool_button_get_type (void) G_GNUC_CONST;
SugarRadioToolButton* sugar_radio_tool_button_new (void);
SugarRadioToolButton* sugar_radio_tool_button_construct (GType object_type);
SugarInvoker* sugar_radio_tool_button_get_invoker (SugarRadioToolButton* self);
const char* sugar_radio_tool_button_get_tooltip (SugarRadioToolButton* self);
void sugar_radio_tool_button_set_tooltip (SugarRadioToolButton* self, const char* value);
const char* sugar_radio_tool_button_get_accelerator (SugarRadioToolButton* self);
void sugar_radio_tool_button_set_accelerator (SugarRadioToolButton* self, const char* value);
void sugar_radio_tool_button_set_icon_name (SugarRadioToolButton* self, const char* value);
SugarIcon* sugar_radio_tool_button_get_icon (SugarRadioToolButton* self);
GType sugar_entry_get_type (void) G_GNUC_CONST;
SugarEntry* sugar_entry_new (void);
SugarEntry* sugar_entry_construct (GType object_type);
const char* sugar_entry_get_primary_icon (SugarEntry* self);
void sugar_entry_set_primary_icon (SugarEntry* self, const char* value);
const char* sugar_entry_get_secondary_icon (SugarEntry* self);
void sugar_entry_set_secondary_icon (SugarEntry* self, const char* value);
gboolean sugar_entry_get_has_clear_button (SugarEntry* self);
void sugar_entry_set_has_clear_button (SugarEntry* self, gboolean value);
GType sugar_table_get_type (void) G_GNUC_CONST;
SugarTable* sugar_table_new (void);
SugarTable* sugar_table_construct (GType object_type);
gint sugar_table_get_width (SugarTable* self);
void sugar_table_set_width (SugarTable* self, gint value);
GType sugar_window_get_type (void) G_GNUC_CONST;
SugarWindow* sugar_window_new (void);
SugarWindow* sugar_window_construct (GType object_type);
gpointer sugar_accelerator_ref (gpointer instance);
void sugar_accelerator_unref (gpointer instance);
GParamSpec* sugar_param_spec_accelerator (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void sugar_value_set_accelerator (GValue* value, gpointer v_object);
void sugar_value_take_accelerator (GValue* value, gpointer v_object);
gpointer sugar_value_get_accelerator (const GValue* value);
GType sugar_accelerator_get_type (void) G_GNUC_CONST;
SugarAccelerator* sugar_accelerator_new (GtkWidget* accel_widget, const char* signal_name);
SugarAccelerator* sugar_accelerator_construct (GType object_type, GtkWidget* accel_widget, const char* signal_name);
const char* sugar_accelerator_get_name (SugarAccelerator* self);
void sugar_accelerator_set_name (SugarAccelerator* self, const char* value);
GType sugar_embedded_menu_get_type (void) G_GNUC_CONST;
SugarEmbeddedMenu* sugar_embedded_menu_new (SugarConnector* palette_connector);
SugarEmbeddedMenu* sugar_embedded_menu_construct (GType object_type, SugarConnector* palette_connector);
void sugar_embedded_menu_insert (SugarEmbeddedMenu* self, GtkWidget* item, gint pos);
GType sugar_embedded_sub_menu_get_type (void) G_GNUC_CONST;
SugarEmbeddedSubMenu* sugar_embedded_sub_menu_new (SugarConnector* palette_connector);
SugarEmbeddedSubMenu* sugar_embedded_sub_menu_construct (GType object_type, SugarConnector* palette_connector);
GType sugar__embeddedmenu_get_type (void) G_GNUC_CONST;
Sugar_EmbeddedMenu* sugar__embeddedmenu_new (SugarConnector* palette_connector);
Sugar_EmbeddedMenu* sugar__embeddedmenu_construct (GType object_type, SugarConnector* palette_connector);
void sugar__embeddedmenu_embed (Sugar_EmbeddedMenu* self, GtkContainer* container);
SugarTrigger* sugar_menu_container_get_menu_trigger (SugarMenuContainer* self);
GType sugar_menu_item_get_type (void) G_GNUC_CONST;
#define SUGAR_MENU_ITEM_SIZE sugar_metrics_get (SUGAR_STANDARD_ICON_SIZE)
SugarMenuItem* sugar_menu_item_new (void);
SugarMenuItem* sugar_menu_item_construct (GType object_type);
SugarTrigger* sugar_menu_item_get_trigger (SugarMenuItem* self);
void sugar_menu_item_set_trigger (SugarMenuItem* self, SugarTrigger* value);
const char* sugar_menu_item_get_accelerator (SugarMenuItem* self);
void sugar_menu_item_set_accelerator (SugarMenuItem* self, const char* value);
const char* sugar_menu_item_get_label (SugarMenuItem* self);
void sugar_menu_item_set_label (SugarMenuItem* self, const char* value);
void sugar_menu_item_set_label_maxlen (SugarMenuItem* self, gint value);
const char* sugar_menu_item_get_icon_name (SugarMenuItem* self);
void sugar_menu_item_set_icon_name (SugarMenuItem* self, const char* value);
SugarIcon* sugar_menu_item_get_icon (SugarMenuItem* self);
GObject* sugar_menu_item_get_tag (SugarMenuItem* self);
void sugar_menu_item_set_tag (SugarMenuItem* self, GObject* value);
GtkAction* sugar_menu_item_get_related_action (SugarMenuItem* self);
void sugar_menu_item_set_related_action (SugarMenuItem* self, GtkAction* value);
void sugar_menu_item_set__selected (SugarMenuItem* self, gboolean value);
void sugar_menu_item_activate_item (SugarMenuItem* self);
GType sugar_menu_get_type (void) G_GNUC_CONST;
void sugar_menu_insert_scrolled (SugarMenu* self, GtkWidget* widget, gint max_row_count, gint max_height, gint pos);
void sugar_menu_insert_action (SugarMenu* self, GtkAction* action, GObject* tag, gint pos);
void sugar_menu_insert_separator (SugarMenu* self, gint pos);
SugarMenu* sugar_menu_new (void);
SugarMenu* sugar_menu_construct (GType object_type);
gint sugar_menu_get_width (SugarMenu* self);
void sugar_menu_set_width (SugarMenu* self, gint value);
GType sugar_label_get_type (void) G_GNUC_CONST;
SugarLabel* sugar_label_new (void);
SugarLabel* sugar_label_construct (GType object_type);
gint sugar_label_get_max_line_count (SugarLabel* self);
void sugar_label_set_max_line_count (SugarLabel* self, gint value);
GType sugar_alignment_get_type (void) G_GNUC_CONST;
SugarAlignment* sugar_alignment_new (void);
SugarAlignment* sugar_alignment_construct (GType object_type);
float sugar_alignment_get_xalign (SugarAlignment* self);
void sugar_alignment_set_xalign (SugarAlignment* self, float value);
float sugar_alignment_get_yalign (SugarAlignment* self);
void sugar_alignment_set_yalign (SugarAlignment* self, float value);
float sugar_alignment_get_xscale (SugarAlignment* self);
void sugar_alignment_set_xscale (SugarAlignment* self, float value);
float sugar_alignment_get_yscale (SugarAlignment* self);
void sugar_alignment_set_yscale (SugarAlignment* self, float value);
gboolean sugar_alignment_get_xignore (SugarAlignment* self);
void sugar_alignment_set_xignore (SugarAlignment* self, gboolean value);
gboolean sugar_alignment_get_yignore (SugarAlignment* self);
void sugar_alignment_set_yignore (SugarAlignment* self, gboolean value);


G_END_DECLS

#endif
