/* toolkit.h generated by valac 0.10.1, the Vala compiler, do not modify */


#ifndef __POLYOL_TOOLKIT_H__
#define __POLYOL_TOOLKIT_H__

#include <glib.h>
#include <polyol/gui.h>
#include <polyol/ds.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <polyol/collab.h>
#include <stdlib.h>
#include <string.h>
#include <polyol/shell.h>

G_BEGIN_DECLS


#define SUGAR_TYPE_ACTIVITY_BUTTON (sugar_activity_button_get_type ())
#define SUGAR_ACTIVITY_BUTTON(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SUGAR_TYPE_ACTIVITY_BUTTON, SugarActivityButton))
#define SUGAR_ACTIVITY_BUTTON_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SUGAR_TYPE_ACTIVITY_BUTTON, SugarActivityButtonClass))
#define SUGAR_IS_ACTIVITY_BUTTON(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SUGAR_TYPE_ACTIVITY_BUTTON))
#define SUGAR_IS_ACTIVITY_BUTTON_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SUGAR_TYPE_ACTIVITY_BUTTON))
#define SUGAR_ACTIVITY_BUTTON_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SUGAR_TYPE_ACTIVITY_BUTTON, SugarActivityButtonClass))

typedef struct _SugarActivityButton SugarActivityButton;
typedef struct _SugarActivityButtonClass SugarActivityButtonClass;
typedef struct _SugarActivityButtonPrivate SugarActivityButtonPrivate;

#define SUGAR_TYPE_ACTIVITY_TOOLBAR_BUTTON (sugar_activity_toolbar_button_get_type ())
#define SUGAR_ACTIVITY_TOOLBAR_BUTTON(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SUGAR_TYPE_ACTIVITY_TOOLBAR_BUTTON, SugarActivityToolbarButton))
#define SUGAR_ACTIVITY_TOOLBAR_BUTTON_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SUGAR_TYPE_ACTIVITY_TOOLBAR_BUTTON, SugarActivityToolbarButtonClass))
#define SUGAR_IS_ACTIVITY_TOOLBAR_BUTTON(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SUGAR_TYPE_ACTIVITY_TOOLBAR_BUTTON))
#define SUGAR_IS_ACTIVITY_TOOLBAR_BUTTON_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SUGAR_TYPE_ACTIVITY_TOOLBAR_BUTTON))
#define SUGAR_ACTIVITY_TOOLBAR_BUTTON_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SUGAR_TYPE_ACTIVITY_TOOLBAR_BUTTON, SugarActivityToolbarButtonClass))

typedef struct _SugarActivityToolbarButton SugarActivityToolbarButton;
typedef struct _SugarActivityToolbarButtonClass SugarActivityToolbarButtonClass;
typedef struct _SugarActivityToolbarButtonPrivate SugarActivityToolbarButtonPrivate;

#define SUGAR_TYPE_ACTIVITY (sugar_activity_get_type ())
#define SUGAR_ACTIVITY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SUGAR_TYPE_ACTIVITY, SugarActivity))
#define SUGAR_ACTIVITY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SUGAR_TYPE_ACTIVITY, SugarActivityClass))
#define SUGAR_IS_ACTIVITY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SUGAR_TYPE_ACTIVITY))
#define SUGAR_IS_ACTIVITY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SUGAR_TYPE_ACTIVITY))
#define SUGAR_ACTIVITY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SUGAR_TYPE_ACTIVITY, SugarActivityClass))

typedef struct _SugarActivity SugarActivity;
typedef struct _SugarActivityClass SugarActivityClass;

#define SUGAR_TYPE_TITLE_ENTRY (sugar_title_entry_get_type ())
#define SUGAR_TITLE_ENTRY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SUGAR_TYPE_TITLE_ENTRY, SugarTitleEntry))
#define SUGAR_TITLE_ENTRY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SUGAR_TYPE_TITLE_ENTRY, SugarTitleEntryClass))
#define SUGAR_IS_TITLE_ENTRY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SUGAR_TYPE_TITLE_ENTRY))
#define SUGAR_IS_TITLE_ENTRY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SUGAR_TYPE_TITLE_ENTRY))
#define SUGAR_TITLE_ENTRY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SUGAR_TYPE_TITLE_ENTRY, SugarTitleEntryClass))

typedef struct _SugarTitleEntry SugarTitleEntry;
typedef struct _SugarTitleEntryClass SugarTitleEntryClass;

#define SUGAR_TYPE_KEEP_BUTTON (sugar_keep_button_get_type ())
#define SUGAR_KEEP_BUTTON(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SUGAR_TYPE_KEEP_BUTTON, SugarKeepButton))
#define SUGAR_KEEP_BUTTON_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SUGAR_TYPE_KEEP_BUTTON, SugarKeepButtonClass))
#define SUGAR_IS_KEEP_BUTTON(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SUGAR_TYPE_KEEP_BUTTON))
#define SUGAR_IS_KEEP_BUTTON_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SUGAR_TYPE_KEEP_BUTTON))
#define SUGAR_KEEP_BUTTON_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SUGAR_TYPE_KEEP_BUTTON, SugarKeepButtonClass))

typedef struct _SugarKeepButton SugarKeepButton;
typedef struct _SugarKeepButtonClass SugarKeepButtonClass;

#define SUGAR_TYPE_STOP_BUTTON (sugar_stop_button_get_type ())
#define SUGAR_STOP_BUTTON(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SUGAR_TYPE_STOP_BUTTON, SugarStopButton))
#define SUGAR_STOP_BUTTON_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SUGAR_TYPE_STOP_BUTTON, SugarStopButtonClass))
#define SUGAR_IS_STOP_BUTTON(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SUGAR_TYPE_STOP_BUTTON))
#define SUGAR_IS_STOP_BUTTON_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SUGAR_TYPE_STOP_BUTTON))
#define SUGAR_STOP_BUTTON_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SUGAR_TYPE_STOP_BUTTON, SugarStopButtonClass))

typedef struct _SugarStopButton SugarStopButton;
typedef struct _SugarStopButtonClass SugarStopButtonClass;
typedef struct _SugarStopButtonPrivate SugarStopButtonPrivate;

#define SUGAR_TYPE_UNDO_BUTTON (sugar_undo_button_get_type ())
#define SUGAR_UNDO_BUTTON(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SUGAR_TYPE_UNDO_BUTTON, SugarUndoButton))
#define SUGAR_UNDO_BUTTON_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SUGAR_TYPE_UNDO_BUTTON, SugarUndoButtonClass))
#define SUGAR_IS_UNDO_BUTTON(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SUGAR_TYPE_UNDO_BUTTON))
#define SUGAR_IS_UNDO_BUTTON_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SUGAR_TYPE_UNDO_BUTTON))
#define SUGAR_UNDO_BUTTON_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SUGAR_TYPE_UNDO_BUTTON, SugarUndoButtonClass))

typedef struct _SugarUndoButton SugarUndoButton;
typedef struct _SugarUndoButtonClass SugarUndoButtonClass;
typedef struct _SugarUndoButtonPrivate SugarUndoButtonPrivate;

#define SUGAR_TYPE_REDO_BUTTON (sugar_redo_button_get_type ())
#define SUGAR_REDO_BUTTON(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SUGAR_TYPE_REDO_BUTTON, SugarRedoButton))
#define SUGAR_REDO_BUTTON_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SUGAR_TYPE_REDO_BUTTON, SugarRedoButtonClass))
#define SUGAR_IS_REDO_BUTTON(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SUGAR_TYPE_REDO_BUTTON))
#define SUGAR_IS_REDO_BUTTON_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SUGAR_TYPE_REDO_BUTTON))
#define SUGAR_REDO_BUTTON_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SUGAR_TYPE_REDO_BUTTON, SugarRedoButtonClass))

typedef struct _SugarRedoButton SugarRedoButton;
typedef struct _SugarRedoButtonClass SugarRedoButtonClass;
typedef struct _SugarRedoButtonPrivate SugarRedoButtonPrivate;

#define SUGAR_TYPE_COPY_BUTTON (sugar_copy_button_get_type ())
#define SUGAR_COPY_BUTTON(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SUGAR_TYPE_COPY_BUTTON, SugarCopyButton))
#define SUGAR_COPY_BUTTON_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SUGAR_TYPE_COPY_BUTTON, SugarCopyButtonClass))
#define SUGAR_IS_COPY_BUTTON(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SUGAR_TYPE_COPY_BUTTON))
#define SUGAR_IS_COPY_BUTTON_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SUGAR_TYPE_COPY_BUTTON))
#define SUGAR_COPY_BUTTON_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SUGAR_TYPE_COPY_BUTTON, SugarCopyButtonClass))

typedef struct _SugarCopyButton SugarCopyButton;
typedef struct _SugarCopyButtonClass SugarCopyButtonClass;
typedef struct _SugarCopyButtonPrivate SugarCopyButtonPrivate;

#define SUGAR_TYPE_PASTE_BUTTON (sugar_paste_button_get_type ())
#define SUGAR_PASTE_BUTTON(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SUGAR_TYPE_PASTE_BUTTON, SugarPasteButton))
#define SUGAR_PASTE_BUTTON_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SUGAR_TYPE_PASTE_BUTTON, SugarPasteButtonClass))
#define SUGAR_IS_PASTE_BUTTON(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SUGAR_TYPE_PASTE_BUTTON))
#define SUGAR_IS_PASTE_BUTTON_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SUGAR_TYPE_PASTE_BUTTON))
#define SUGAR_PASTE_BUTTON_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SUGAR_TYPE_PASTE_BUTTON, SugarPasteButtonClass))

typedef struct _SugarPasteButton SugarPasteButton;
typedef struct _SugarPasteButtonClass SugarPasteButtonClass;
typedef struct _SugarPasteButtonPrivate SugarPasteButtonPrivate;
typedef struct _SugarKeepButtonPrivate SugarKeepButtonPrivate;

#define SUGAR_TYPE_SHARE_BUTTON (sugar_share_button_get_type ())
#define SUGAR_SHARE_BUTTON(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SUGAR_TYPE_SHARE_BUTTON, SugarShareButton))
#define SUGAR_SHARE_BUTTON_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SUGAR_TYPE_SHARE_BUTTON, SugarShareButtonClass))
#define SUGAR_IS_SHARE_BUTTON(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SUGAR_TYPE_SHARE_BUTTON))
#define SUGAR_IS_SHARE_BUTTON_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SUGAR_TYPE_SHARE_BUTTON))
#define SUGAR_SHARE_BUTTON_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SUGAR_TYPE_SHARE_BUTTON, SugarShareButtonClass))

typedef struct _SugarShareButton SugarShareButton;
typedef struct _SugarShareButtonClass SugarShareButtonClass;
typedef struct _SugarShareButtonPrivate SugarShareButtonPrivate;
typedef struct _SugarTitleEntryPrivate SugarTitleEntryPrivate;

#define SUGAR_TYPE_ALERT_BIN (sugar_alert_bin_get_type ())
#define SUGAR_ALERT_BIN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SUGAR_TYPE_ALERT_BIN, SugarAlertBin))
#define SUGAR_ALERT_BIN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SUGAR_TYPE_ALERT_BIN, SugarAlertBinClass))
#define SUGAR_IS_ALERT_BIN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SUGAR_TYPE_ALERT_BIN))
#define SUGAR_IS_ALERT_BIN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SUGAR_TYPE_ALERT_BIN))
#define SUGAR_ALERT_BIN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SUGAR_TYPE_ALERT_BIN, SugarAlertBinClass))

typedef struct _SugarAlertBin SugarAlertBin;
typedef struct _SugarAlertBinClass SugarAlertBinClass;
typedef struct _SugarAlertBinPrivate SugarAlertBinPrivate;

#define SUGAR_TYPE_ALERT (sugar_alert_get_type ())
#define SUGAR_ALERT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SUGAR_TYPE_ALERT, SugarAlert))
#define SUGAR_IS_ALERT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SUGAR_TYPE_ALERT))
#define SUGAR_ALERT_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), SUGAR_TYPE_ALERT, SugarAlertIface))

typedef struct _SugarAlert SugarAlert;
typedef struct _SugarAlertIface SugarAlertIface;

#define SUGAR_TYPE_MESSAGE_ALERT (sugar_message_alert_get_type ())
#define SUGAR_MESSAGE_ALERT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SUGAR_TYPE_MESSAGE_ALERT, SugarMessageAlert))
#define SUGAR_MESSAGE_ALERT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SUGAR_TYPE_MESSAGE_ALERT, SugarMessageAlertClass))
#define SUGAR_IS_MESSAGE_ALERT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SUGAR_TYPE_MESSAGE_ALERT))
#define SUGAR_IS_MESSAGE_ALERT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SUGAR_TYPE_MESSAGE_ALERT))
#define SUGAR_MESSAGE_ALERT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SUGAR_TYPE_MESSAGE_ALERT, SugarMessageAlertClass))

typedef struct _SugarMessageAlert SugarMessageAlert;
typedef struct _SugarMessageAlertClass SugarMessageAlertClass;
typedef struct _SugarMessageAlertPrivate SugarMessageAlertPrivate;

#define SUGAR_TYPE_CONFIRMATION_ALERT (sugar_confirmation_alert_get_type ())
#define SUGAR_CONFIRMATION_ALERT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SUGAR_TYPE_CONFIRMATION_ALERT, SugarConfirmationAlert))
#define SUGAR_CONFIRMATION_ALERT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SUGAR_TYPE_CONFIRMATION_ALERT, SugarConfirmationAlertClass))
#define SUGAR_IS_CONFIRMATION_ALERT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SUGAR_TYPE_CONFIRMATION_ALERT))
#define SUGAR_IS_CONFIRMATION_ALERT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SUGAR_TYPE_CONFIRMATION_ALERT))
#define SUGAR_CONFIRMATION_ALERT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SUGAR_TYPE_CONFIRMATION_ALERT, SugarConfirmationAlertClass))

typedef struct _SugarConfirmationAlert SugarConfirmationAlert;
typedef struct _SugarConfirmationAlertClass SugarConfirmationAlertClass;
typedef struct _SugarConfirmationAlertPrivate SugarConfirmationAlertPrivate;

#define SUGAR_TYPE_TIMEOUT_ALERT (sugar_timeout_alert_get_type ())
#define SUGAR_TIMEOUT_ALERT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SUGAR_TYPE_TIMEOUT_ALERT, SugarTimeoutAlert))
#define SUGAR_TIMEOUT_ALERT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SUGAR_TYPE_TIMEOUT_ALERT, SugarTimeoutAlertClass))
#define SUGAR_IS_TIMEOUT_ALERT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SUGAR_TYPE_TIMEOUT_ALERT))
#define SUGAR_IS_TIMEOUT_ALERT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SUGAR_TYPE_TIMEOUT_ALERT))
#define SUGAR_TIMEOUT_ALERT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SUGAR_TYPE_TIMEOUT_ALERT, SugarTimeoutAlertClass))

typedef struct _SugarTimeoutAlert SugarTimeoutAlert;
typedef struct _SugarTimeoutAlertClass SugarTimeoutAlertClass;
typedef struct _SugarTimeoutAlertPrivate SugarTimeoutAlertPrivate;

#define SUGAR_TYPE_NOTIFY_ALERT (sugar_notify_alert_get_type ())
#define SUGAR_NOTIFY_ALERT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SUGAR_TYPE_NOTIFY_ALERT, SugarNotifyAlert))
#define SUGAR_NOTIFY_ALERT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SUGAR_TYPE_NOTIFY_ALERT, SugarNotifyAlertClass))
#define SUGAR_IS_NOTIFY_ALERT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SUGAR_TYPE_NOTIFY_ALERT))
#define SUGAR_IS_NOTIFY_ALERT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SUGAR_TYPE_NOTIFY_ALERT))
#define SUGAR_NOTIFY_ALERT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SUGAR_TYPE_NOTIFY_ALERT, SugarNotifyAlertClass))

typedef struct _SugarNotifyAlert SugarNotifyAlert;
typedef struct _SugarNotifyAlertClass SugarNotifyAlertClass;
typedef struct _SugarNotifyAlertPrivate SugarNotifyAlertPrivate;
typedef struct _SugarActivityPrivate SugarActivityPrivate;

struct _SugarActivityButton {
	SugarToolButton parent_instance;
	SugarActivityButtonPrivate * priv;
};

struct _SugarActivityButtonClass {
	SugarToolButtonClass parent_class;
};

struct _SugarActivityToolbarButton {
	SugarToolbarButton parent_instance;
	SugarActivityToolbarButtonPrivate * priv;
};

struct _SugarActivityToolbarButtonClass {
	SugarToolbarButtonClass parent_class;
};

struct _SugarStopButton {
	SugarToolButton parent_instance;
	SugarStopButtonPrivate * priv;
};

struct _SugarStopButtonClass {
	SugarToolButtonClass parent_class;
};

struct _SugarUndoButton {
	SugarToolButton parent_instance;
	SugarUndoButtonPrivate * priv;
};

struct _SugarUndoButtonClass {
	SugarToolButtonClass parent_class;
};

struct _SugarRedoButton {
	SugarToolButton parent_instance;
	SugarRedoButtonPrivate * priv;
};

struct _SugarRedoButtonClass {
	SugarToolButtonClass parent_class;
};

struct _SugarCopyButton {
	SugarToolButton parent_instance;
	SugarCopyButtonPrivate * priv;
};

struct _SugarCopyButtonClass {
	SugarToolButtonClass parent_class;
};

struct _SugarPasteButton {
	SugarToolButton parent_instance;
	SugarPasteButtonPrivate * priv;
};

struct _SugarPasteButtonClass {
	SugarToolButtonClass parent_class;
};

struct _SugarKeepButton {
	SugarToolButton parent_instance;
	SugarKeepButtonPrivate * priv;
};

struct _SugarKeepButtonClass {
	SugarToolButtonClass parent_class;
};

struct _SugarShareButton {
	SugarComboToolButton parent_instance;
	SugarShareButtonPrivate * priv;
};

struct _SugarShareButtonClass {
	SugarComboToolButtonClass parent_class;
};

struct _SugarTitleEntry {
	GtkToolItem parent_instance;
	SugarTitleEntryPrivate * priv;
};

struct _SugarTitleEntryClass {
	GtkToolItemClass parent_class;
};

struct _SugarAlertBin {
	GtkEventBox parent_instance;
	SugarAlertBinPrivate * priv;
};

struct _SugarAlertBinClass {
	GtkEventBoxClass parent_class;
};

struct _SugarAlertIface {
	GTypeInterface parent_iface;
};

struct _SugarMessageAlert {
	GtkHBox parent_instance;
	SugarMessageAlertPrivate * priv;
};

struct _SugarMessageAlertClass {
	GtkHBoxClass parent_class;
};

struct _SugarConfirmationAlert {
	SugarMessageAlert parent_instance;
	SugarConfirmationAlertPrivate * priv;
};

struct _SugarConfirmationAlertClass {
	SugarMessageAlertClass parent_class;
};

struct _SugarTimeoutAlert {
	SugarMessageAlert parent_instance;
	SugarTimeoutAlertPrivate * priv;
};

struct _SugarTimeoutAlertClass {
	SugarMessageAlertClass parent_class;
};

struct _SugarNotifyAlert {
	SugarMessageAlert parent_instance;
	SugarNotifyAlertPrivate * priv;
};

struct _SugarNotifyAlertClass {
	SugarMessageAlertClass parent_class;
};

struct _SugarActivity {
	GObject parent_instance;
	SugarActivityPrivate * priv;
};

struct _SugarActivityClass {
	GObjectClass parent_class;
	void (*write_file) (SugarActivity* self, const char* file_path, gboolean transfer_ownership);
};


GType sugar_activity_button_get_type (void) G_GNUC_CONST;
SugarActivityButton* sugar_activity_button_new (SugarJobject* jobject);
SugarActivityButton* sugar_activity_button_construct (GType object_type, SugarJobject* jobject);
GType sugar_activity_toolbar_button_get_type (void) G_GNUC_CONST;
GType sugar_activity_get_type (void) G_GNUC_CONST;
SugarActivityToolbarButton* sugar_activity_toolbar_button_new (SugarActivity* activity);
SugarActivityToolbarButton* sugar_activity_toolbar_button_construct (GType object_type, SugarActivity* activity);
GType sugar_title_entry_get_type (void) G_GNUC_CONST;
SugarTitleEntry* sugar_activity_toolbar_button_get_title (SugarActivityToolbarButton* self);
GType sugar_keep_button_get_type (void) G_GNUC_CONST;
SugarKeepButton* sugar_activity_toolbar_button_get_keep (SugarActivityToolbarButton* self);
GType sugar_stop_button_get_type (void) G_GNUC_CONST;
SugarStopButton* sugar_stop_button_new (void);
SugarStopButton* sugar_stop_button_construct (GType object_type);
GType sugar_undo_button_get_type (void) G_GNUC_CONST;
SugarUndoButton* sugar_undo_button_new (void);
SugarUndoButton* sugar_undo_button_construct (GType object_type);
GType sugar_redo_button_get_type (void) G_GNUC_CONST;
SugarRedoButton* sugar_redo_button_new (void);
SugarRedoButton* sugar_redo_button_construct (GType object_type);
GType sugar_copy_button_get_type (void) G_GNUC_CONST;
SugarCopyButton* sugar_copy_button_new (void);
SugarCopyButton* sugar_copy_button_construct (GType object_type);
GType sugar_paste_button_get_type (void) G_GNUC_CONST;
SugarPasteButton* sugar_paste_button_new (void);
SugarPasteButton* sugar_paste_button_construct (GType object_type);
SugarKeepButton* sugar_keep_button_new (SugarJobject* jobject);
SugarKeepButton* sugar_keep_button_construct (GType object_type, SugarJobject* jobject);
GType sugar_share_button_get_type (void) G_GNUC_CONST;
SugarShareButton* sugar_share_button_new (SugarConnection* connection);
SugarShareButton* sugar_share_button_construct (GType object_type, SugarConnection* connection);
SugarTitleEntry* sugar_title_entry_new (SugarJobject* jobject);
SugarTitleEntry* sugar_title_entry_construct (GType object_type, SugarJobject* jobject);
GtkEntry* sugar_title_entry_get_entry (SugarTitleEntry* self);
GType sugar_alert_bin_get_type (void) G_GNUC_CONST;
GType sugar_alert_get_type (void) G_GNUC_CONST;
void sugar_alert_bin_push (SugarAlert* alert);
void sugar_alert_bin_pop (SugarAlert* alert);
SugarAlertBin* sugar_alert_bin_new (void);
SugarAlertBin* sugar_alert_bin_construct (GType object_type);
GType sugar_message_alert_get_type (void) G_GNUC_CONST;
SugarMessageAlert* sugar_message_alert_new (const char* title_text, const char* message_text, const char* icon_name);
SugarMessageAlert* sugar_message_alert_construct (GType object_type, const char* title_text, const char* message_text, const char* icon_name);
void sugar_message_alert_add_button (SugarMessageAlert* self, gint response_id, const char* label, const char* icon_name, gint timeout);
GType sugar_confirmation_alert_get_type (void) G_GNUC_CONST;
SugarConfirmationAlert* sugar_confirmation_alert_new (const char* title_text, const char* message_text, const char* icon_name);
SugarConfirmationAlert* sugar_confirmation_alert_construct (GType object_type, const char* title_text, const char* message_text, const char* icon_name);
GType sugar_timeout_alert_get_type (void) G_GNUC_CONST;
SugarTimeoutAlert* sugar_timeout_alert_new (const char* title_text, const char* message_text, const char* icon_name, gint timeout);
SugarTimeoutAlert* sugar_timeout_alert_construct (GType object_type, const char* title_text, const char* message_text, const char* icon_name, gint timeout);
GType sugar_notify_alert_get_type (void) G_GNUC_CONST;
SugarNotifyAlert* sugar_notify_alert_new (const char* title_text, const char* message_text, const char* icon_name, gint timeout);
SugarNotifyAlert* sugar_notify_alert_construct (GType object_type, const char* title_text, const char* message_text, const char* icon_name, gint timeout);
SugarActivity* sugar_activity_new (gboolean use_journal, gboolean use_sharing);
SugarActivity* sugar_activity_construct (GType object_type, gboolean use_journal, gboolean use_sharing);
void sugar_activity_write_file (SugarActivity* self, const char* file_path, gboolean transfer_ownership);
SugarJobject* sugar_activity_get_jobject (SugarActivity* self);
SugarShell* sugar_activity_get_shell (SugarActivity* self);
SugarJournal* sugar_activity_get_journal (SugarActivity* self);
SugarConnection* sugar_activity_get_connection (SugarActivity* self);
gboolean sugar_activity_get_resumed (SugarActivity* self);


G_END_DECLS

#endif
